# Generated by Django 5.0.1 on 2024-05-16 23:42

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('nomer_id', models.IntegerField(blank=True, null=True, verbose_name='Номер сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('book_cat_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Категории книг',
                'verbose_name_plural': 'Категории книг',
                'ordering': ['nomer_id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(max_length=255, verbose_name='Название книги')),
                ('opisanie_full', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание  полное')),
                ('opisanie_mini', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание краткое')),
                ('book_slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template_name', models.CharField(blank=True, max_length=70, verbose_name='Выбор шаблона')),
                ('book_cat', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='book.book_cat', verbose_name='книга относится к категории')),
            ],
            options={
                'verbose_name': 'Книги',
                'verbose_name_plural': 'Книги',
                'ordering': ['-created_at'],
            },
        ),
    ]
