# Generated by Django 5.0.1 on 2024-05-18 12:42

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otziv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('name_block2', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность')),
                ('text_block', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('template_name', models.CharField(blank=True, help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.", max_length=70, verbose_name='Выбор шаблона')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prostopages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_block', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок h1')),
                ('text_block', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Описание страницы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='prostopages', verbose_name='Картинка')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Url')),
                ('template_name', models.CharField(blank=True, help_text="Пример: 'book/prostopages.html'. Если не указано,  система будет использовать 'prostopages/prostopages.html'.", max_length=70, verbose_name='Выбор шаблона')),
                ('title_us', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тайтл')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Дескрипшон')),
            ],
            options={
                'verbose_name': 'Простую страницу',
                'verbose_name_plural': 'Простые страницы',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prostopages', verbose_name='Картинка'),
        ),
        migrations.AddField(
            model_name='book',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='prostopages', verbose_name='Картинка'),
        ),
    ]
