# Generated by Django 5.0.1 on 2024-05-19 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_slider'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.SlugField(default=1, max_length=255, unique=True, verbose_name='Url'),
            preserve_default=False,
        ),
    ]
