# Generated by Django 5.0.1 on 2024-05-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_blog_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bestseller',
            field=models.BooleanField(default=True, verbose_name='Бестселлер'),
        ),
        migrations.AddField(
            model_name='book',
            name='futured',
            field=models.BooleanField(default=True, verbose_name='Будущее'),
        ),
        migrations.AddField(
            model_name='book',
            name='latest',
            field=models.BooleanField(default=True, verbose_name='Последние'),
        ),
        migrations.AddField(
            model_name='book',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name='Цена без акции'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='book',
            name='procent',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name='Процент скидки'),
        ),
        migrations.AddField(
            model_name='book',
            name='skidka',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=6, null=True, verbose_name='Скидка в рублях'),
        ),
        migrations.AddField(
            model_name='book',
            name='special',
            field=models.BooleanField(default=True, verbose_name='Спешл'),
        ),
    ]
