# Generated by Django 5.0.1 on 2024-05-19 09:19

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_book_bestseller_book_futured_book_latest_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OtzivBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rayting', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Интересно')),
                ('rayting2', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('rayting3', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Сюжет')),
                ('rayting_seredina', models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='Средний рейтинг')),
                ('name_aftor', models.CharField(max_length=255, verbose_name='Имя автора')),
                ('otziv_plus', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Плюсы')),
                ('otziv_minus', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Минусы')),
                ('opisanie', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='', null=True, verbose_name='Комментарий')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(blank=True, null=True, verbose_name='Перезаписать дату отзыва')),
                ('book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.book', verbose_name='выбрать товар по id')),
                ('zakazchik', models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-id'],
            },
        ),
    ]
