# Generated by Django 5.0.1 on 2024-05-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_bookfile_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл fb2'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл epub'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл RTF'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл Mobi'),
        ),
    ]
