# Generated by Django 5.0.1 on 2024-05-20 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_bookfile_file_alter_bookfile_file2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл fb2'),
        ),
        migrations.AddField(
            model_name='book',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл epub'),
        ),
        migrations.AddField(
            model_name='book',
            name='file3',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл RTF'),
        ),
        migrations.AddField(
            model_name='book',
            name='file4',
            field=models.FileField(blank=True, null=True, upload_to='book_files', verbose_name='Файл Mobi'),
        ),
        migrations.DeleteModel(
            name='BookFile',
        ),
    ]
