# Generated by Django 5.0.1 on 2024-05-20 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_book_avtor_alter_book_image2_book_avtors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_avtor',
            name='name_block',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='book_avtor',
            name='name_block2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='book_avtor',
            name='name_block3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество'),
        ),
    ]
